# 自动求导机制

In [19]:
import torch

In [20]:
#定义一个随机矩阵,且设置为可以求导
x = torch.randn(3,4, requires_grad=True)
x

tensor([[ 1.7007, -0.0272, -0.1920,  0.2136],
        [ 0.8740, -0.2553, -1.3568,  1.6570],
        [-0.2719, -0.6680,  0.3492,  0.3121]], requires_grad=True)

In [21]:
b = torch.randn(3,4, requires_grad=True)
b

tensor([[-1.2041,  1.3179,  2.3835,  0.2246],
        [ 0.7199,  1.2835, -0.0465,  0.3981],
        [-0.2150, -0.0652, -0.8572,  0.9794]], requires_grad=True)

In [22]:
t = x + b

In [23]:
y = t.sum()
y

tensor(7.2543, grad_fn=<SumBackward0>)

In [24]:
print(b.grad)

None


只需要在最后一步调用.backward()，进行反向传播

In [25]:
y.backward()
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

注意：如果不清空grad，则会进行累加

# 一个线性回归例子

构造一组输入x，和其对应的标签y

In [28]:
import numpy as np

In [29]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)
x_train.shape

(11, 1)

In [37]:
y_values = [2*i + 1 for i in range(11)]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
y_train.shape
y

tensor(7.2543, grad_fn=<SumBackward0>)

In [31]:
import torch
import torch.nn as nn

线性回归模型

In [33]:
class LinearModule(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearModule, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        out = self.linear(x)
        return out

In [34]:
input_dim = 1
output_dim = 1

model = LinearModule(input_dim, output_dim)
model

LinearModule(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

参数+损失函数的定义：

In [38]:
epochs = 1000   #训练一千次
learn_rate = 0.01
optim = torch.optim.SGD(model.parameters(), learn_rate)
lossFunc = nn.MSELoss()    #基础的损失函数

训练模型

In [39]:
for epoch in range(epochs):
    epoch +=1
    #转化tensor
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)

    optim.zero_grad()   #梯度清零
    outputs = model(inputs) #正向传播
    loss = lossFunc(outputs, labels)    #损失函数计算
    loss.backward() #反向传播
    optim.step()    #更新权重，进行优化
    if epoch%50 == 0:
        print(f"epoch:{epoch}, loss:{loss}")

epoch:50, loss:0.24371109902858734
epoch:100, loss:0.13900357484817505
epoch:150, loss:0.07928242534399033
epoch:200, loss:0.04521973431110382
epoch:250, loss:0.02579166740179062
epoch:300, loss:0.014710629358887672
epoch:350, loss:0.008390411734580994
epoch:400, loss:0.004785576369613409
epoch:450, loss:0.0027295106556266546
epoch:500, loss:0.0015568111557513475
epoch:550, loss:0.0008879583911038935
epoch:600, loss:0.0005064551369287074
epoch:650, loss:0.0002888568851631135
epoch:700, loss:0.00016475748270750046
epoch:750, loss:9.39724559430033e-05
epoch:800, loss:5.3596893849316984e-05
epoch:850, loss:3.0569495720556006e-05
epoch:900, loss:1.743840766721405e-05
epoch:950, loss:9.944312296283897e-06
epoch:1000, loss:5.6720773500273935e-06
